// src/utils/dummyData.js

/* ===========================
   더미 데이터 관리
   =========================== */

// 지역 중심점들
export const YANGJAE = { lat: 37.484722, lng: 127.034722 };
export const SEOCHO_GANGNAM = { lat: 37.4979, lng: 127.0276 };

// 거리 계산 함수
export const distKm = (a, b) => {
  const R = 6371;
  const dLat = ((b.lat - a.lat) * Math.PI) / 180;
  const dLng = ((b.lng - a.lng) * Math.PI) / 180;
  const la1 = (a.lat * Math.PI) / 180;
  const la2 = (b.lat * Math.PI) / 180;
  const h =
    Math.sin(dLat / 2) ** 2 +
    Math.cos(la1) * Math.cos(la2) * Math.sin(dLng / 2) ** 2;
  return 2 * R * Math.asin(Math.min(1, Math.sqrt(h)));
};

// 지역 확인 함수들
export const isNearYangjae = (lat, lng, radiusKm = 2.5) =>
  distKm({ lat, lng }, YANGJAE) <= radiusKm;

export const isNearSeochoGangnam = (lat, lng, radiusKm = 3.0) =>
  distKm({ lat, lng }, SEOCHO_GANGNAM) <= radiusKm;

// URL 파라미터 체크
export const forceYangjae =
  new URLSearchParams(window.location.search).get("yangjae") === "1";
export const forceSeochoGangnam =
  new URLSearchParams(window.location.search).get("seocho") === "1";

// 양재 더미 데이터
export const getYangjaeDummies = () => [
  {
    id: "pv-dummy-yg-1",
    kakaoId: "pv-dummy-yg-1",
    name: "양재동 화훼공판장 주차장",
    address: "서울 서초구 양재동 232-4",
    lat: 37.4849,
    lng: 127.0362,
    price: 500,
    charge: 500,
    operateTimes: [{ start: "00:00", end: "24:00" }],
    note: "",
    type: "PRIVATE",
    isLocal: true,
    _localOnly: true,
    distanceKm: null,
    etaMin: null,
    leavingSoon: false,
  },
  {
    id: "pv-dummy-yg-2",
    kakaoId: "pv-dummy-yg-2",
    name: "양재근린공원주차장",
    address: "서울 서초구 양재동 244-2",
    lat: 37.4716,
    lng: 127.0414,
    price: 800,
    charge: 800,
    operateTimes: [{ start: "00:00", end: "24:00" }],
    note: "",
    type: "PRIVATE",
    isLocal: true,
    _localOnly: true,
    distanceKm: null,
    etaMin: null,
    leavingSoon: false,
  },
  {
    id: "pv-dummy-yg-3",
    kakaoId: "pv-dummy-yg-3",
    name: "양재동부동산중개 앞 주차장(구간162)",
    address: "서울 서초구 강남대로8길 69",
    lat: 37.469,
    lng: 127.0441,
    price: 300,
    charge: 300,
    operateTimes: [{ start: "00:00", end: "24:00" }],
    note: "",
    type: "PRIVATE",
    isLocal: true,
    _localOnly: true,
    distanceKm: null,
    etaMin: null,
    leavingSoon: false,
  },
  {
    id: "pv-dummy-yg-4",
    kakaoId: "pv-dummy-yg-4",
    name: "양재빌리지 앞 주차장 (구획 23-6)",
    address: "서울 서초구 마방로2길 15-15",
    lat: 37.4735,
    lng: 127.0401,
    price: 300,
    charge: 300,
    operateTimes: [{ start: "00:00", end: "24:00" }],
    note: "",
    type: "PRIVATE",
    isLocal: true,
    _localOnly: true,
    distanceKm: null,
    etaMin: null,
    leavingSoon: false,
  },
];

// 서초/강남 더미 데이터
export const getSeochoGangnamDummies = () => {
  const leavingSoonIds = window.dummyLeavingSoonIds || [];
  
  return [
  // 서초구 주차장들
  {
    id: "pub-dummy-sc-1",
    kakaoId: "pub-dummy-sc-1", 
    name: "양재 공영 주차장",
    address: "서울특별시 양재동 90-2",
    lat: 37.4847,
    lng: 127.0347,
    price: 1800,
    charge: 1800,
    operateTimes: [{ start: "00:00", end: "24:00" }],
    note: "평일 주간권, 평일 12시간권, 휴일 12시간권",
    type: "PUBLIC",
    isLocal: false,
    _localOnly: true,
    distanceKm: null,
    etaMin: null,
    leavingSoon: false,
  },
  {
    id: "prv-dummy-sc-2",
    kakaoId: "prv-dummy-sc-2",
    name: "제이프라자빌딩 민영 주차장", 
    address: "서울특별시 서초구 방우리로37길 18",
    lat: 37.4936,
    lng: 127.0286,
    price: 6000,
    charge: 6000,
    operateTimes: [{ start: "00:00", end: "24:00" }],
    note: "휴일 뿜뿜폰, 평일 당일권(화~금)",
    type: "PRIVATE",
    isLocal: true,
    _localOnly: true,
    distanceKm: null,
    etaMin: null,
    leavingSoon: false,
  },
  {
    id: "prv-dummy-sc-3",
    kakaoId: "prv-dummy-sc-3",
    name: "드림 민영 주차장",
    address: "서울 강남구 개포동 1238-5",
    lat: 37.4812,
    lng: 127.0598,
    price: 6000,
    charge: 6000,
    operateTimes: [{ start: "00:00", end: "24:00" }],
    note: "휴일 당일권",
    type: "PRIVATE", 
    isLocal: true,
    _localOnly: true,
    distanceKm: null,
    etaMin: null,
    leavingSoon: false,
  },
  {
    id: "prv-dummy-sc-4", 
    kakaoId: "prv-dummy-sc-4",
    name: "카카오T 양재근린공원 주차장",
    address: "서울 서초구 양재동 244-2",
    lat: 37.4716,
    lng: 127.0414,
    price: 4500,
    charge: 4500,
    operateTimes: [{ start: "00:00", end: "24:00" }],
    note: "신아권, 평일 당일권, 휴일 뿜뿜폰",
    type: "PRIVATE",
    isLocal: true,
    _localOnly: true,
    distanceKm: null,
    etaMin: null,
    leavingSoon: false,
  },
  {
    id: "pub-dummy-sc-5",
    kakaoId: "pub-dummy-sc-5",
    name: "트르파티 구룡고원 공영 주차장",
    address: "서울 서초구 능헌로5길 29",
    lat: 37.4801,
    lng: 127.0425,
    price: 1800,
    charge: 1800,
    operateTimes: [{ start: "00:00", end: "24:00" }],
    note: "",
    type: "PUBLIC",
    isLocal: false,
    _localOnly: true,
    distanceKm: null,
    etaMin: null,
    leavingSoon: false,
  },
  {
    id: "prv-dummy-sc-6",
    kakaoId: "prv-dummy-sc-6",
    name: "하이파킹 동산마을 주차장",
    address: "강남대로8길 77",
    lat: 37.4695,
    lng: 127.0388,
    price: 3000,
    charge: 3000,
    operateTimes: [{ start: "00:00", end: "24:00" }],
    note: "",
    type: "PRIVATE",
    isLocal: true,
    _localOnly: true,
    distanceKm: null,
    etaMin: null,
    leavingSoon: false,
  },
  {
    id: "prv-dummy-sc-7",
    kakaoId: "prv-dummy-sc-7",
    name: "양재 민영 주차장",
    address: "서울 서초구 양재동 353-3",
    lat: 37.4823,
    lng: 127.0359,
    price: 4000,
    charge: 4000,
    operateTimes: [{ start: "10:00", end: "22:00" }],
    note: "",
    type: "PRIVATE",
    isLocal: true,
    _localOnly: true,
    distanceKm: null,
    etaMin: null,
    leavingSoon: false,
  },
  {
    id: "prv-dummy-sc-8",
    kakaoId: "prv-dummy-sc-8",
    name: "코수육 주차장",
    address: "서울 서초구 강남대로2길 12",
    lat: 37.4967,
    lng: 127.0289,
    price: 0, // 무료
    charge: 0,
    operateTimes: [{ start: "00:00", end: "24:00" }],
    note: "",
    type: "PRIVATE",
    isLocal: true,
    _localOnly: true,
    distanceKm: null,
    etaMin: null,
    leavingSoon: false,
  },
  {
    id: "prv-dummy-sc-9",
    kakaoId: "prv-dummy-sc-9",
    name: "아이파킹 이마트 양재점 주차장",
    address: "서울특별시 서초구 매헌로 16",
    lat: 37.4729,
    lng: 127.0356,
    price: 0, // 무료
    charge: 0,
    operateTimes: [{ start: "10:00", end: "22:00" }],
    note: "",
    type: "PRIVATE",
    isLocal: true,
    _localOnly: true,
    distanceKm: null,
    etaMin: null,
    leavingSoon: false,
  },
  {
    id: "prv-dummy-sc-10",
    kakaoId: "prv-dummy-sc-10",
    name: "아이파킹 하이마레 등 주차장",
    address: "서울특별시 서초구 매헌로 16",
    lat: 37.4738,
    lng: 127.0368,
    price: 0, // 무료
    charge: 0,
    operateTimes: [{ start: "00:00", end: "24:00" }],
    note: "",
    type: "PRIVATE",
    isLocal: true,
    _localOnly: true,
    distanceKm: null,
    etaMin: null,
    leavingSoon: false,
  },
  // 강남구 주차장들  
  {
    id: "pub-dummy-gn-1",
    kakaoId: "pub-dummy-gn-1",
    name: "나우빌 건너편 주차장(구획16-22-11)",
    address: "서울 서초구 바우뫼로39길 88-11",
    lat: 37.4892,
    lng: 127.0195,
    price: 1800,
    charge: 1800,
    operateTimes: [{ start: "00:00", end: "24:00" }],
    note: "",
    type: "PUBLIC",
    isLocal: false,
    _localOnly: true,
    distanceKm: null,
    etaMin: null,
    leavingSoon: false,
  },
  {
    id: "pub-dummy-gn-2",
    kakaoId: "pub-dummy-gn-2",
    name: "삼익양재빌라1 앞 주차장(구간 92)",
    address: "서울 서초구 바우뫼로23길 34",
    lat: 37.4876,
    lng: 127.0208,
    price: 1800,
    charge: 1800,
    operateTimes: [{ start: "00:00", end: "24:00" }],
    note: "",
    type: "PUBLIC",
    isLocal: false,
    _localOnly: true,
    distanceKm: null,
    etaMin: null,
    leavingSoon: false,
  },
  {
    id: "pub-dummy-gn-3",
    kakaoId: "pub-dummy-gn-3",
    name: "롯데빌라 a동 앞 주차장(구획 127-1)",
    address: "서울 서초구 양재천로15길 13",
    lat: 37.4765,
    lng: 127.0198,
    price: 1800,
    charge: 1800,
    operateTimes: [{ start: "00:00", end: "06:30" }],
    note: "",
    type: "PUBLIC",
    isLocal: false,
    _localOnly: true,
    distanceKm: null,
    etaMin: null,
    leavingSoon: false,
  },
  {
    id: "pub-dummy-gn-4",
    kakaoId: "pub-dummy-gn-4",
    name: "교창 앞 주차장(구간 182)",
    address: "서울 서초구 매헌로16길 20",
    lat: 37.46801,
    lng: 127.035575,
    price: 1800,
    charge: 1800,
    operateTimes: [{ start: "00:00", end: "08:30" }],
    note: "",
    type: "PUBLIC",
    isLocal: false,
    _localOnly: true,
    distanceKm: null,
    etaMin: null,
    leavingSoon: false,
  },
  {
    id: "pub-dummy-gn-5",
    kakaoId: "pub-dummy-gn-5",
    name: "장원빌라 앞(구획 174-2)",
    address: "서울 서초구 동산로10길 64",
    lat: 37.4789,
    lng: 127.0312,
    price: 1800,
    charge: 1800,
    operateTimes: [{ start: "00:00", end: "09:00" }],
    note: "",
    type: "PUBLIC",
    isLocal: false,
    _localOnly: true,
    distanceKm: null,
    etaMin: null,
    leavingSoon: false,
  },
  {
    id: "pub-dummy-gn-6",
    kakaoId: "pub-dummy-gn-6",
    name: "충원성버빌 옆 주차장(구획 42-4)",
    address: "서울 서초구 마방로6길 7-19",
    lat: 37.4721,
    lng: 127.0398,
    price: 1800,
    charge: 1800,
    operateTimes: [{ start: "00:00", end: "09:00" }],
    note: "",
    type: "PUBLIC",
    isLocal: false,
    _localOnly: true,
    distanceKm: null,
    etaMin: null,
    leavingSoon: false,
  },
  // 추가 주차장들 (두 번째 이미지)
  {
    id: "prv-dummy-sc-11",
    kakaoId: "prv-dummy-sc-11",
    name: "해인빌딩 주차장",
    address: "서울특별시 서초구 강남대로 163",
    lat: 37.4912,
    lng: 127.0268,
    price: 4000,
    charge: 4000,
    operateTimes: [{ start: "08:00", end: "22:00" }],
    note: "",
    type: "PRIVATE",
    isLocal: true,
    _localOnly: true,
    distanceKm: null,
    etaMin: null,
    leavingSoon: false,
  },
  {
    id: "prv-dummy-sc-12",
    kakaoId: "prv-dummy-sc-12",
    name: "시민 민영 주차장",
    address: "서울 서초구 양재동 80-9",
    lat: 37.4845,
    lng: 127.0351,
    price: 5000,
    charge: 5000,
    operateTimes: [{ start: "09:00", end: "22:30" }],
    note: "",
    type: "PRIVATE",
    isLocal: true,
    _localOnly: true,
    distanceKm: null,
    etaMin: null,
    leavingSoon: false,
  },
  {
    id: "prv-dummy-sc-13",
    kakaoId: "prv-dummy-sc-13",
    name: "양재 민영 주차장",
    address: "서울특별시 서초구 남부순환로354길 23",
    lat: 37.4758,
    lng: 127.0389,
    price: 6000,
    charge: 6000,
    operateTimes: [{ start: "00:00", end: "24:00" }],
    note: "",
    type: "PRIVATE",
    isLocal: true,
    _localOnly: true,
    distanceKm: null,
    etaMin: null,
    leavingSoon: false,
  },
  {
    id: "prv-dummy-sc-14",
    kakaoId: "prv-dummy-sc-14",
    name: "숯불 민영 주차장",
    address: "서울 강남구 개포동 1229-2",
    lat: 37.4823,
    lng: 127.0612,
    price: 6000,
    charge: 6000,
    operateTimes: [{ start: "07:00", end: "24:00" }],
    note: "",
    type: "PRIVATE",
    isLocal: true,
    _localOnly: true,
    distanceKm: null,
    etaMin: null,
    leavingSoon: false,
  },
  {
    id: "prv-dummy-sc-15",
    kakaoId: "prv-dummy-sc-15",
    name: "덕수 민영 주차장",
    address: "서울특별시 강남구 논현로 84",
    lat: 37.5087,
    lng: 127.0298,
    price: 6000,
    charge: 6000,
    operateTimes: [{ start: "07:00", end: "24:00" }],
    note: "",
    type: "PRIVATE",
    isLocal: true,
    _localOnly: true,
    distanceKm: null,
    etaMin: null,
    leavingSoon: false,
  },
  {
    id: "prv-dummy-sc-16",
    kakaoId: "prv-dummy-sc-16",
    name: "원드스토오피스텔 민영 주차장",
    address: "서울특별시 서초구 논현로 79",
    lat: 37.4934,
    lng: 127.0274,
    price: 4000,
    charge: 4000,
    operateTimes: [{ start: "06:00", end: "24:00" }],
    note: "",
    type: "PRIVATE",
    isLocal: true,
    _localOnly: true,
    distanceKm: null,
    etaMin: null,
    leavingSoon: false,
  },
  {
    id: "prv-dummy-sc-17",
    kakaoId: "prv-dummy-sc-17",
    name: "유덕 민영 주차장",
    address: "서울특별시 강남구 논현로16길 15",
    lat: 37.5065,
    lng: 127.0312,
    price: 3500,
    charge: 3500,
    operateTimes: [{ start: "08:00", end: "20:00" }],
    note: "",
    type: "PRIVATE",
    isLocal: true,
    _localOnly: true,
    distanceKm: null,
    etaMin: null,
    leavingSoon: false,
  },
  {
    id: "prv-dummy-sc-18",
    kakaoId: "prv-dummy-sc-18",
    name: "상호 민영 주차장",
    address: "서울 서초구 양재동 269-2",
    lat: 37.4787,
    lng: 127.0398,
    price: 6000,
    charge: 6000,
    operateTimes: [{ start: "00:00", end: "24:00" }],
    note: "",
    type: "PRIVATE",
    isLocal: true,
    _localOnly: true,
    distanceKm: null,
    etaMin: null,
    leavingSoon: false,
  },
  {
    id: "pub-dummy-sc-19",
    kakaoId: "pub-dummy-sc-19",
    name: "양재시민의숲 동측 공영 주차장",
    address: "서울특별시 양재동 237 매헌시민의숲",
    lat: 37.4723,
    lng: 127.0445,
    price: 3000,
    charge: 3000,
    operateTimes: [{ start: "00:00", end: "24:00" }],
    note: "",
    type: "PUBLIC",
    isLocal: false,
    _localOnly: true,
    distanceKm: null,
    etaMin: null,
    leavingSoon: false,
  },
  {
    id: "pub-dummy-sc-20",
    kakaoId: "pub-dummy-sc-20",
    name: "언남문화체육센터 공영 주차장",
    address: "동산로13길 35",
    lat: 37.4778,
    lng: 127.0356,
    price: 1800,
    charge: 1800,
    operateTimes: [{ start: "00:00", end: "24:00" }],
    note: "",
    type: "PUBLIC",
    isLocal: false,
    _localOnly: true,
    distanceKm: null,
    etaMin: null,
    leavingSoon: false,
  },
  {
    id: "pub-dummy-sc-21",
    kakaoId: "pub-dummy-sc-21",
    name: "범제교육센터 주차장",
    address: "서울특별시 서초구 동산로15길 23",
    lat: 37.4798,
    lng: 127.0378,
    price: 0, // 무료
    charge: 0,
    operateTimes: [{ start: "08:00", end: "21:00" }],
    note: "",
    type: "PUBLIC",
    isLocal: false,
    _localOnly: true,
    distanceKm: null,
    etaMin: null,
    leavingSoon: false,
  },
  {
    id: "pub-dummy-sc-22",
    kakaoId: "pub-dummy-sc-22",
    name: "양재근린공원 공영 주차장",
    address: "서초구 서울특별시 서초구 언남길 15-6",
    lat: 37.4716,
    lng: 127.0414,
    price: 1800,
    charge: 1800,
    operateTimes: [{ start: "00:00", end: "24:00" }],
    note: "",
    type: "PUBLIC",
    isLocal: false,
    _localOnly: true,
    distanceKm: null,
    etaMin: null,
    leavingSoon: false,
  },
  {
    id: "pub-dummy-sc-23",
    kakaoId: "pub-dummy-sc-23",
    name: "양재2동주민센터 공영 주차장",
    address: "강남대로12길 44",
    lat: 37.4934,
    lng: 127.0289,
    price: 1800,
    charge: 1800,
    operateTimes: [{ start: "07:00", end: "21:00" }],
    note: "",
    type: "PUBLIC",
    isLocal: false,
    _localOnly: true,
    distanceKm: null,
    etaMin: null,
    leavingSoon: false,
  },
  {
    id: "pub-dummy-sc-24",
    kakaoId: "pub-dummy-sc-24",
    name: "매헌윤봉길의사기념관 공영 주차장",
    address: "서울특별시 서초구 매헌로 99",
    lat: 37.4732,
    lng: 127.0387,
    price: 1800,
    charge: 1800,
    operateTimes: [{ start: "09:00", end: "22:00" }],
    note: "",
    type: "PUBLIC",
    isLocal: false,
    _localOnly: true,
    distanceKm: null,
    etaMin: null,
    leavingSoon: false,
  },
  {
    id: "pub-dummy-sc-25",
    kakaoId: "pub-dummy-sc-25",
    name: "양재시민의숲매헌역 주차장",
    address: "서울특별시 서초구 매헌로 99",
    lat: 37.4729,
    lng: 127.0398,
    price: 0, // 무료
    charge: 0,
    operateTimes: [{ start: "08:00", end: "20:59" }],
    note: "",
    type: "PUBLIC",
    isLocal: false,
    _localOnly: true,
    distanceKm: null,
    etaMin: null,
    leavingSoon: false,
  },
  {
    id: "pub-dummy-sc-26",
    kakaoId: "pub-dummy-sc-26",
    name: "양재시민의숲 매헌역 공영 주차장",
    address: "서초구 서울특별시 서초구 양재동 237-2",
    lat: 37.4723,
    lng: 127.0445,
    price: 3000,
    charge: 3000,
    operateTimes: [{ start: "00:00", end: "24:00" }],
    note: "",
    type: "PUBLIC",
    isLocal: false,
    _localOnly: true,
    distanceKm: null,
    etaMin: null,
    leavingSoon: false,
  },
  {
    id: "prv-dummy-sc-27",
    kakaoId: "prv-dummy-sc-27",
    name: "테팩스빌딩 주차장",
    address: "서울특별시 서초구 동산로 7",
    lat: 37.4789,
    lng: 127.0356,
    price: 4000,
    charge: 4000,
    operateTimes: [{ start: "07:00", end: "21:00" }],
    note: "",
    type: "PRIVATE",
    isLocal: true,
    _localOnly: true,
    distanceKm: null,
    etaMin: null,
    leavingSoon: false,
  },
  {
    id: "prv-dummy-sc-28",
    kakaoId: "prv-dummy-sc-28",
    name: "그린도트 더프라자곡물 프레인지 양재점 주차장",
    address: "서울특별시 서초구 동산로2길 16",
    lat: 37.4767,
    lng: 127.0389,
    price: 18000,
    charge: 18000,
    operateTimes: [{ start: "00:00", end: "23:59" }],
    note: "",
    type: "PRIVATE",
    isLocal: true,
    _localOnly: true,
    distanceKm: null,
    etaMin: null,
    leavingSoon: false,
  },
  {
    id: "prv-dummy-sc-29",
    kakaoId: "prv-dummy-sc-29",
    name: "원 민영 주차장",
    address: "서울 서초구 양재동 331-4",
    lat: 37.4798,
    lng: 127.0398,
    price: 6000,
    charge: 6000,
    operateTimes: [{ start: "07:00", end: "21:00" }],
    note: "",
    type: "PRIVATE",
    isLocal: true,
    _localOnly: true,
    distanceKm: null,
    etaMin: null,
    leavingSoon: false,
  },
  {
    id: "prv-dummy-sc-30",
    kakaoId: "prv-dummy-sc-30",
    name: "AT센터 주차장",
    address: "서울특별시 서초구 강남대로 27",
    lat: 37.4923,
    lng: 127.0276,
    price: 4200,
    charge: 4200,
    operateTimes: [{ start: "05:00", end: "24:00" }],
    note: "",
    type: "PRIVATE",
    isLocal: true,
    _localOnly: true,
    distanceKm: null,
    etaMin: null,
    leavingSoon: false,
  },
  {
    id: "prv-dummy-sc-31",
    kakaoId: "prv-dummy-sc-31",
    name: "상보 민영 주차장",
    address: "서울 서초구 양재동 328-7",
    lat: 37.4812,
    lng: 127.0423,
    price: 6000,
    charge: 6000,
    operateTimes: [{ start: "09:30", end: "23:30" }],
    note: "",
    type: "PRIVATE",
    isLocal: true,
    _localOnly: true,
    distanceKm: null,
    etaMin: null,
    leavingSoon: false,
  },
  {
    id: "prv-dummy-sc-32",
    kakaoId: "prv-dummy-sc-32",
    name: "양재동351 민영 주차장",
    address: "서울특별시 서초구 강남대로6길 4",
    lat: 37.4891,
    lng: 127.0256,
    price: 4000,
    charge: 4000,
    operateTimes: [{ start: "00:00", end: "24:00" }],
    note: "",
    type: "PRIVATE",
    isLocal: true,
    _localOnly: true,
    distanceKm: null,
    etaMin: null,
    leavingSoon: false,
  },
  {
    id: "prv-dummy-sc-33",
    kakaoId: "prv-dummy-sc-33",
    name: "현대유로 민영 주차장",
    address: "서울특별시 서초구 강남대로6길 36-11",
    lat: 37.4887,
    lng: 127.0234,
    price: 4000,
    charge: 4000,
    operateTimes: [{ start: "07:00", end: "22:00" }],
    note: "",
    type: "PRIVATE",
    isLocal: true,
    _localOnly: true,
    distanceKm: null,
    etaMin: null,
    leavingSoon: false,
  },
  {
    id: "pub-dummy-sc-34",
    kakaoId: "pub-dummy-sc-34",
    name: "나태지私 공영 주차장",
    address: "경기 과천시 주암동 70-6",
    lat: 37.4654,
    lng: 127.0298,
    price: 0, // 무료
    charge: 0,
    operateTimes: [{ start: "00:00", end: "24:00" }],
    note: "",
    type: "PUBLIC",
    isLocal: false,
    _localOnly: true,
    distanceKm: null,
    etaMin: null,
    leavingSoon: false,
  }
].map(parking => ({
  ...parking,
  leavingSoon: leavingSoonIds.includes(parking.id)
}));
};

// 배열 중복 제거 유틸리티
export const uniqueById = (arr) => {
  const m = new Map();
  arr.forEach((x) => {
    const key = String(x.id);
    if (!m.has(key)) m.set(key, x);
  });
  return Array.from(m.values());
};
